circle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,6 +8,7 @@ jobs:
       # using custom image, see .circleci/images/primary/Dockerfile
       - image: mongo:3.6.6
       - image: amazon/aws-cli
+      - image: subfuzion/netcat
     #working_directory: /go/src/github.com/circleci/cci-demo-docker
 
     environment:
@@ -19,9 +20,9 @@ jobs:
       - run:
           name: Waiting for MongoDB to be ready
           command: |
-            for i in `seq 1 10`;
+            for i in `seq 1 3`;
             do
-              nc -z localhost 27017 && echo Success && exit 0
+              netcat -z localhost 27017 && echo Success && exit 0
               echo -n .
               sleep 1
             done
@@ -29,17 +30,17 @@ jobs:
 
       - run: mkdir -p $TEST_RESULTS
 
-      - run:
-          name: Run unit tests
-          environment:
-            DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
-            DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
-          command: |
-            set -ou pipefail
-            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
-            # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
-            # without this option script will return success regardless of testing result due to pipe after test command
-            make test | tee ${TEST_RESULTS}/go-test.out
+      # - run:
+      #     name: Run unit tests
+      #     environment:
+      #       DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
+      #       DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
+      #     command: |
+      #       set -ou pipefail
+      #       trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
+      #       # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
+      #       # without this option script will return success regardless of testing result due to pipe after test command
+      #       make test | tee ${TEST_RESULTS}/go-test.out
 
       - setup_remote_docker
 
@@ -65,6 +66,7 @@ jobs:
           name: Log-in to docker
           command: |
             aws ecr get-login
+            
 
       # - run:
       #     name: Build service
